# load libraries
library(shiny)
library(ggplot2)
library(DT)
library(shinyjs)
library(Cairo)
library(viridis)
library(ComplexHeatmap)
library(RColorBrewer)
library(data.table)
library(dplyr)
library(shinythemes)
library(meta)
library(gplots)
library(openxlsx)
library(shinycssloaders)
library(shinyTree)
library(slickR)

# common settings
options(shiny.usecairo=T)
options(stringsAsFactors = F)
# load('app_data.RData')
load('app_data.RData')